---
title: | 
  | Phil/LPS 31 Introduction to Inductive Logic
  | Lecture 15
author: |
    | David Mwakima
    | dmwakima@uci.edu
    | Department of Logic and Philosophy of Science
    | University of California, Irvine
date: "May 22nd 2023"
output: beamer_presentation
header-includes:
  - \setbeamertemplate{footline}[page number]
---

# Topics

\begin{itemize}
\item Part 1: Decision Problems under Ignorance
\begin{itemize}
\item Ordinal Utilities
\item Dominance Principles
\item Maximin
\end{itemize}
\item Part 2: Decision Problems under Information
\begin{itemize}
\item Cardinal Utilities
\item Expected Utility and Risk
\item Principles of Rational Choice under Information
\end{itemize}
\end{itemize}


# Recap: Decision Problems: Acts, States, Consequences, Utility/Loss Functions

>- Specify the states of the dinner party example.

>- Specify the acts that you may take.

>- Suppose you do not know what the host will serve, how would you decide what wine to bring? You are making a decision under ignorance or lack of information.

>- Suppose you know that there are even odds that the host will serve red meat or white meat, how would you decide what to bring? You are making a decision under information.

>- In any case, what is the rational choice for you?

# Recap: Decision Problems: Acts, States, Consequences, Utility/Loss Functions

>- Specify the states of President Biden's decision problem.

>- Specify the acts that President Biden may take

>- Suppose President Biden after returning from his trip from Japan does not knows how the leaders of U.S. House of Representative will take his deal proposal. President Biden is faced with a decision under ignorance or lack of information.

>- Suppose that President Biden knows the odds are 3:5 that the U.S. House of Representative Leaders will take his deal. President Biden here is faced with a decision under information or certainty. 

>- In any case, what is the rational choice for President Biden?

# Classes of Decision Problems

>- In order to articulate the principles of rational choice in decision problems. We shall distinguish between decision problems under \textcolor{red}{ignorance} from decision problems under \textcolor{red}{information}.

>- Decision problems under ignorance are also known as decision problems under lack of information or decision problems under uncertainty. The relevant sense of "information" here is information about the \textcolor{red}{probability distribution} of states. The relevant sense of "uncertainty" here is that we don't \textcolor{red}{know} \textcolor{red}{the probabilities} with which the states will occur \textcolor{red}{with certainty}.

>- Decision problems under information are also known as decision problems under certainty or risk. The relevant sense of "certainty" here is that one is certain about the \textcolor{red}{probability distribution} of states. So one \textcolor{red}{can compute the risk} associated with taking a decision.

# {.flexbox .vcenter}

### Part 2: Decision Problems under Ignorance

# Ordinal Utilities

>- The principles of rational choice \textcolor{red}{under ignorance} can be formulated by \textcolor{red}{ranking} or \textcolor{red}{ordering} utilities based on the desirability of their consequences. This leads to the concept of \textcolor{red}{ordinal utilities}.

>- In what follows, we shall use lower case $u$ to denote the utility of an act $A$ given a state $S$ and write $u(A \,| \,S)$

>- We write $A_{i} \succ A_{j}$ to mean Act $i$ is \textcolor{red}{preferred more} than Act $j$.

>- We write $A_{i} \sim A_{j}$ to mean Act $i$ is \textcolor{red}{preferred equally} to Act $j$.

# Ordinal Utilities

>- Let $A_{1}, A_{2}, A_{3}$ denote the acts of bringing white wine, red wine or rosé to the dinner party, respectively. And let $S_{1}, S_{2}$ denote the state in which the host serves fish or chicken, respectively.

>- Suppose that given $S_{1}$, we can \textcolor{red}{order} our preferences as $A_{1} \succ A_{3} \succ A_{2}$. This means that if our host serves fish, we would prefer bringing white wine more than we would prefer bringing either rosé or red wine; and we would prefer to bring rosé more than we would prefer to bring red wine.

>- An \textcolor{red}{ordinal} utility function is an assignment of utilities to acts that \textcolor{red}{respects the preference ordering} or ranking of the acts.

>- Consider the following utility function: $u(A_{1} \, |\, S_{1})  = 4$, $u(A_{2} \, | \, S_{1}) = 2$ and $u(A_{3} \, | \, S_{1}) = 3$

>- Here we see that $4 > 3 > 2$. So this utility function respects the preference ordering of the acts. 4, 3 and 2 are \textcolor{red}{ordinal utilities}.


# Ordinal Utilities

>- Suppose now that the host serves chicken, $S_{2}$. You think that if the host serves chicken you'd much rather bring white wine than either red wine or rosé. Assume also that if you can't find white wine at Trader Joe's you'd much rather bring rosé than red wine.

>- Exercise. \begin{itemize} \item[1] Write down the preference ordering on the Acts. \item[2] Using the following set of utility values $\{1, 3, 5\}$ determine your ordinal utility function. \item[3] Verify that your utility function respects your preference ordering. \end{itemize}

# Properties of Ordinal Utilities

>- Utilities on an ordinal scale have certain properties: \begin{itemize} 
\item[(1)] They are unique up to \textcolor{red}{strictly increasing} transformations.
\item[(2)] You \textcolor{red}{can't multiply or add} ordinal utilities. A fancy word for this you will often see is that transformations of ordinal utilities are not linear.
\item[(3)] From (2) we \textcolor{red}{can't calculate expected utility} using ordinal utilities. See Barrett and Huttegger Section 4.9.
\item[(4)] Provide \textcolor{red}{no information} about \textcolor{red}{the strength of preferences}.
\end{itemize}

# Making Decisions with Ordinal Utilities

>- From the previous exercises we obtain the following desirability table for acts based on our ordinal utility function. \begin{center}
\begin{tabular}{|c |c |c|}\hline
    & Fish  & Chicken \\ \hline
White & 4 & 5 \\ 
Red  & 2 & 1 \\ 
Rosé & 3 & 3 \\ \hline
\end{tabular}
\end{center}

>- Suppose that you are faced with a decision problem under ignorance of bringing either white wine, red wine or rosé. How would you decide?

>- Decision theorists propose the following principles: \begin{itemize}
\item Decide on the basis of \textcolor{red}{the weak dominance principle}.
\item Decide on the basis of \textcolor{red}{the strong dominance principle}.
\item Decide on the basis of \textcolor{red}{the maximin principle}.
\end{itemize}

# Strict and Weak Dominance Principles

>- \begin{center}
\begin{tabular}{|c |c |c|}\hline
    & Fish  & Chicken \\ \hline
White & 4 & 5 \\ 
Red  & 2 & 1 \\ 
Rosé & 3 & 3 \\ \hline
\end{tabular}
\end{center}

>- Here \textcolor{red}{no matter} what the true state of world turns out to be we'd prefer to bring white wine rather than either red wine or rosé. 

>- We say that $A_{1}$ "\textcolor{red}{dominates}" both $A_{2}$ and $A_{3}$.

>- Similarly $A_{3}$ "\textcolor{red}{dominates}" $A_{2}$.

>- A widely accepted \textcolor{red}{dominance principle} in decision theory prescribes that \textcolor{red}{dominated acts must not be chosen}.

# Strict and Weak Dominance Principle

>- An act can be dominant in one of two ways: which we call \textcolor{red}{strict} and \textcolor{red}{weak}.

>- We denote \textcolor{red}{weak dominance} using $\succeq$ and write $A_{i} \succeq A_{j}$ to mean $A_{i}$ \textcolor{blue}{weakly dominates} $A_{j}$.

>- We denote \textcolor{red}{strict dominance} using $\succ$ and write $A_{i}  \succ A_{j}$ to mean $A_{i}$ \textcolor{blue}{strictly dominates} $A_{j}$

>- \textbf{Weak Dominance}: $A_{i} \succeq A_{j}$ if and only if $u(A_{i} | S) \geq u(A_{j} | S)$ for \textcolor{red}{every} state $S$ (at least as good)

>- \textbf{Strict Dominance}: $A_{i} \succ A_{j}$ if and only if (1) $u(A_{i} | S_{n}) \geq u(A_{j} | S_{n})$ for \textcolor{red}{every} state $S_{n}$ (at least as good) and (2) there exists a state $S_{m}$ such that $u(A_{i} | S_{m}) > u(A_{j} | S_{m})$ (at least one better).

# Strict and Weak Dominance Principle

>- \begin{center}
\begin{tabular}{|c |c |c|}\hline
    & Fish  & Chicken \\ \hline
White & 4 & 5 \\ 
Red  & 2 & 1 \\ 
Rosé & 3 & 3 \\ \hline
\end{tabular}
\end{center}

>- Exercise. Refer to the desirability table for the dinner party example to answer the following questions. \begin{itemize}
\item Does $A_{1} \succeq A_{3}$?
\item Does $A_{1} \succ A_{2}$?
\item Does $A_{3} \succeq A_{2}$?
\end{itemize}

# Strict and Weak Dominance Principle

>- \begin{center}
\begin{tabular}{|c |c |c| c |}\hline
    & Fish  & Chicken & Lamb \\ \hline
White & 3 & 4 & 1 \\ 
Red  & 2 & 1 & 4 \\ 
Rosé & 3 & 4 & 4 \\ \hline
\end{tabular}
\end{center}

>- Exercise. Refer to the desirability table for the dinner party example to answer the following questions. \begin{itemize}
\item Does $A_{1} \succeq A_{3}$?
\item Does $A_{3} \succ A_{1}$?
\item Does $A_{3} \succeq A_{2}$?
\item Does $A_{3} \succ A_{2}$?
\item Does the strong dominance principle imply the weak dominance principle?
\end{itemize}

# Strict and Weak Dominance Principle

>- Now suppose \begin{center}
\begin{tabular}{|c |c |c| c |}\hline
    & Fish  & Chicken & Lamb \\ \hline
White & 3 & 4 & 4 \\ 
Red  & 2 & 1 & 4 \\ 
Rosé & 3 & 4 & 4 \\ \hline
\end{tabular}
\end{center}

>- Exercise. Refer to the desirability table for the dinner party example above to answer the following questions. \begin{itemize}
\item Does $A_{1} \succeq A_{3}$?
\item Does $A_{3} \succeq A_{1}$?
\item Does $A_{1} \succ A_{2}$?
\item Does $A_{3} \succ A_{2}$?
\item How would you decide in this case?
\end{itemize}

# Maximin Principle

>- The last principle for decision problems under ignorance is known as the \textcolor{red}{maximin principle}.

>- The maximin principle focuses on the worst possible outcome of each alternative act. Essentially, we're asking \textcolor{red}{what's the worst that can happen?}

>- According to this principle, one should \textcolor{red}{MAX}imise the \textcolor{red}{MIN}imal value obtainable with each act. If the worst possible outcome of one alternative is better than that of another, then the former should be chosen.


# Maximin Principle

>- \begin{center}
\begin{tabular}{|c |c |c| c |}\hline
    & Fish  & Chicken & Lamb \\ \hline
Red  & 0 & 1 & 4 \\ 
Rosé & 1 & 2 & 1 \\ \hline
\end{tabular}
\end{center}

>- Exercise. Refer to the desirability table for the dinner party example above to answer the following questions. \begin{itemize}
\item What is the worst possible outcome for $A_{2}$? How about $A_{3}$? 
\item Does $A_{3} \succeq A_{2}$?
\item Why would an agent choose $A_{3}$?
\end{itemize}

>- There are other principles of rational choice in the context of decisions under ignorance. But we shall not cover them in this introductory course. The book by Martin Peterson \textit{An Introduction to Decision Theory} is highly recommended for this.

# {.flexbox .vcenter}

### Part 1: Decision Problems under Information


# Cardinal Utilities

>- The principles of rational choice under information require an agent to \textcolor{red}{make use} of this information to inform their decision.

>- The available information which the agent is assumed to know with certainty is \textcolor{red}{the probability distribution of the states}. Here the agent is modeling the states of the world as a random variable.

>- This means that the agent can also calculate the expected value of functions of these states, namely, consequences of an act.

>- However, not just any concept of utility will do. We have seen that because ordinal utilities cannot be added or multiplied, we cannot use them to calculate expected values. Further ordinal utilities do not quantify the strength of preference, they simply respect the ordering of our preferences.

# Cardinal Utilities

>- Cardinal utilities are the right concept of utility to quantify the strength of preference.

>- They also enjoy the right kind of properties that make calculations of expected values possible.

>- Some of these properties are: \begin{itemize}\item[(1)] Like ordinal utilities, cardinal utilities are unique up to \textcolor{red}{strictly increasing} transformations. \item[(2)] Cardinal utilities are invariant under \textcolor{red}{positive} scaling and \textcolor{red}{positive} translation. Barrett and Huttegger call this \textcolor{red}{positive affine transformation} So cardinal utilities are like hours and seconds. \item[(3)] From (2) we \textcolor{red}{can calculate expected utilities} using cardinal utilities.
\item[(4)] Provide \textcolor{red}{information} about \textcolor{red}{the strength of preferences}.\end{itemize}

# Expected Utility

>- The expected utility of an act is the weighted average of the consequences of that act where the weights on the consequences are determined by the probability distribution on states.

>- Suppose that the states in a decision problem are listed as $\{S_{1}, S_{2}, \dots, S_{n}\}$ and that there is a probability distribution on the states that assigns them probabilities $\{P(S_{1}), P(S_{2}), \dots, P(S_{n})\}$. Then the expected utility of an act $A$
\[
\begin{aligned}
U(A) &= u(A | S_{1})P(S_{1}) + u(A | S_{2})P(S_{2}) + \dots + u(A | S_{n})P(S_{n}) \nonumber \\
        &= \sum_{i}^{n} u(A \,|\,S_{i})P(S_{i})
\end{aligned}
\]

>- In other words, take the utility of that action given each state of the word multiplied by the probability that the state obtains and sum everything up.

# Expected Utility

>- Consider the dinner party example again. This time the entries are cardinal utilities. \begin{center}
\begin{tabular}{|c |c |c|}\hline
    & Fish  & Chicken \\ \hline
White & 4 & 5 \\ 
Red  & 2 & 1 \\ 
Rosé & 3 & 3 \\ \hline
\end{tabular}
\end{center}

>- Exercise.\begin{itemize} Suppose you know that there are even odds that the host will serve fish or chicken calculate the expected value of $A_{1}$, $A_{2}$ and $A_{3}$ \end{itemize}


# Maximizing Expected Utility

>- The \textcolor{red}{cardinal} principle (you see what I did there?) of decision problems under risk is the \textcolor{red}{principle of maximizing expected utility} if you're using a cardinal utility function.

>- This means that in any decision problem, choose the act that maximizes expected utility with respect to your probability distribution on states.

# Maximizing Expected Utility

>- For the following exercise, refer to the following desirability table. \begin{center}
\begin{tabular}{|c |c |c| c |}\hline
    & Fish & Chicken & Lamb \\ \hline
White & 3 & 4 & 1 \\ 
Red  & 2 & 1 & 4 \\ 
Rosé & 3 & 4 & 4 \\ \hline
\end{tabular}
\end{center}

>- Suppose you know that because of rising tariffs on fish imports from Canada and recent shortages of lamb, you host is likely to serve chicken with probability 0.8, fish with probability 0.15 and lamb with probability 0.05. What wine should you choose to bring to the dinner party according to the principle of maximizing expected utility?

# Minimizing Risk



