---
title: | 
  | Phil/LPS 31 Introduction to Inductive Logic
  | Lecture 14
author: |
    | David Mwakima
    | dmwakima@uci.edu
    | Department of Logic and Philosophy of Science
    | University of California, Irvine
date: "May 19th 2023"
output: beamer_presentation
header-includes:
  - \setbeamertemplate{footline}[page number]
---

# Topics

\begin{itemize}
\item Recap: Is inductive logic possible?
\item Introduction to Decision Theory
\item Utilities and Losses
\end{itemize}

# Recap: Is inductive logic possible?

Here's Hume (1748) \textit{An Enquiry Concerning Human Understanding}: 
\bigskip
\begin{quote}
In vain do you pretend to have learned the nature of bodies from your past experience. Their secret nature, and consequently all their effects and influence, may change without any change in their sensible qualities. This happens sometimes, and with regard to some objects: why may it not happen always, and with regard to all objects? \textcolor{red}{What logic}, what process or argument secures you against this supposition? My practice, you say, refutes my doubts. But you mistake the purport of my question. As an agent, I am quite satisfied in the point; but as a philosopher...I want to learn the foundation of this inference. 
\end{quote}


# Recap: Is inductive logic possible?

>- We think that is better to use the scientific method to make predictions rather than custom or habit, astrology, crystal gazing, palmistry, even simply guessing. But why are these rules of inductive inference bad?

>- In the case of deductive logic, the justification of the rules of inference there was that the good rules of inference are precisely those rules of inference that are truth-preserving. But we have seen that these rules are truth-preserving because they are non-ampliative.

>- Do we have a similar criterion for selecting the inductive rules of inference that are good? In other words, \textcolor{red}{is inductive logic possible?}

# Is probability the very guide of life?

\begin{quote} But to us, probability is the very guide of life.\end{quote} Joseph Butler (1736) \textit{The Analogy of Religion, Natural and Revealed, to the Constitution and Course of Nature}


# Is probability the true logic for this world?

\begin{quote}
They say that Understanding ought to work by the rules of right reason. These rules are, or ought to be, contained in Logic; but the actual science of Logic is conversant at present only with things either certain, impossible, or entirely doubtful, none of which (fortunately) we have to reason on. Therefore the \textcolor{red}{the True Logic} for this world is the Calculus of Probabilities, which takes account of the magnitude of the probability (which is, or which ought to be in a reasonable man's mind). This branch of Math., which is generally thought to favor gambling, dicing, and wagering, and therefore highly immoral, is the only "Mathematics for Practical [People]', as we ought to be.
\end{quote} James Clerk Maxwell's Letter to Lewis Campbell, c. July 1850

# Introduction to Decision Theory

>- Following Rudolf Carnap (1971) "Inductive Logic and Rational Decisions", we say \textcolor{red}{inductive logic is the logic of reliable on-going scientific inquiry or rational deliberation}.

>- The goal, then, is to characterize good inductive rules of inference as the rules that \textcolor{red}{maximize expected utility} or \textcolor{red}{minimize risk}.

>- Such a characterization will give us a precise of way of saying what we mean when we say that good rules of inductive inference are those rules that lead to "favorable consequences most of the time."

>- The way we do this is \textcolor{red}{by merging}: (1) probability theory (which gives us the "most of the time part" using \textcolor{red}{expected value}) and (2) decision theory (which gives principles we can use to "evaluate consequences", namely the concepts of \textcolor{red}{utility} and \textcolor{red}{loss}).


# Introduction to Decision Theory

>- The synthesis of (1) probability theory and (2) decision theory is part of \textcolor{red}{a promising and currently on-going} approach to formulating principles of inductive logic as the logic of reliable on-going scientific inquiry or rational deliberation.

>- In fact, this kind of synthesis was at the foundation of the Bayesian interpretation of probability and the application of Bayesian methods in inductive inference.

>- Here's how Rev. Thomas Bayes famous for Bayes' Theorem put it in the seminal "An Essay towards solving a problem in the Doctrine of Chances" published in 1763.
\bigskip
\begin{quote}
The probability of any event is the ratio between the value at which an
expectation depending on the happening of the event ought to be computed, and the chance of the thing expected upon it’s happening. 
\end{quote} 

# Introduction to Decision Theory

>- In Proposition 2 of that essay he proves that:\bigskip
\begin{quote}
If a person has an expectation depending on the happening of an event, the probability of the event is to the probability of its failure as his loss if it fails to his gain if it happens.
\end{quote}

>- Essentially, what Thomas Bayes is saying here is that \textcolor{red}{rational decision making/deliberation} and the \textcolor{red}{probability} one assigns to events \textcolor{red}{are linked}. 

>- This is quite remarkable! It means that you can: (1) use \textcolor{red}{the expected value} of the losses/gains on your decisions \textcolor{red}{to calibrate} your probabilities; and (2) you can use probabilities to decide upon which actions are "rational" to take based on their expected losses (risks) or expected gains.

>- Let us see how we can do this more formally.

# Decision Problems: Illustration 1

>- Suppose you are invited to a dinner party and your host asks you to bring some wine. You have to choose between white wine or red wine. It is also known that red wine goes well with red meat (like beef, lamb and veal) while white wine goes well with white meat (like chicken or fish). So you want the wine you bring to match the type of dish that will be served.


# Decision Problems: Illustration 1

>- You cannot bring both to the dinner party because you're on a budget. So you are faced with \textcolor{red}{a decision problem} which we may represent in the following \textcolor{red}{decision table} (the left table) and corresponding
\textcolor{red}{desirability table} (the right table).

\bigskip
\begin{columns}
\begin{column}{0.65\textwidth}
\begin{tabular}{| c| c| c|}\hline
    & Fish  & Lamb \\ \hline
White & The right wine & The wrong wine \\ 
Red  & An odd wine & The right wine \\ \hline
\end{tabular}
\end{column}

\begin{column}{0.35\textwidth}
\begin{tabular}{|c |c |c|}\hline
    & Fish  & Lamb \\ \hline
White & 5 & 2 \\ 
Red  & 1 & 5 \\ \hline
\end{tabular}
\end{column}
\end{columns}

# Decision Problems: Illustration 2

>- NPR Morning Edition reported, "Democrats urge Biden to use his constitutional right to raise the debt limit" because the U.S. House of Representative leaders are threatening to default if President Biden doesn't give in to them.

>- Treasure Department Secretary Janet Yellen says that if President Biden invoked the 14th Amendment, it would create a constitutional crisis.

>- The President is faced with two choices to make sure that the American Federal Government lives up to its obligations and avoids default: invoke the 14th amendment or reach a deal with U.S. House of Representative leaders.

# Decision Problems: Illustration 2

>- President Biden has a decision problem.\bigskip

\begin{columns}
\begin{column}{0.50\textwidth}
\begin{tabular}{|p{0.2\textwidth}| p{0.2\textwidth} p{0.3\textwidth}|} \hline
       & Deal  &  No Deal \\
Invoke$^{c}$ & Default$^{c}$ & Default \\ 
Invoke & Default$^{c}$ & Crisis \\ 
\hline
\end{tabular}
\end{column}

\begin{column}{0.50\textwidth}
\begin{tabular}{|p{0.2\textwidth}| p{0.2\textwidth} p{0.3\textwidth}|}\hline
       & Deal  & No Deal \\ 
Invoke$^{c}$ & 0 & -10 \\ 
Invoke  & -1 & -1 \\ \hline
\end{tabular}
\end{column}
\end{columns}


# Decision Problems: States, Acts

>- Every decision problem has four components: \begin{itemize} \item States \item Acts \item Consequences \item Utility/Loss functions 
\end{itemize}

>- \textcolor{red}{States} correspond to how the world is or could be. They represent all the possibilities that an agent/decision maker can find themselves in. It is a partition of what the agent considers epistemically accessible and relevant to their decision problem. We use $S$, with or without numerical subscripts to denote states. 

>- \textcolor{red}{Acts} correspond to choices that an agent may make when faced with a decision problem. It is assumed that the space of possible acts is a partition of the space of choices that an agent may take, in the sense that the choices are \textcolor{red}{mutually exclusive}. We use $A$, with or without numerical subscripts to denote acts.

# Decision Problems: Consequences and Utility Functions

>- \textcolor{red}{Consequences} are the joint outcomes of choosing to act one way \textcolor{red}{given} one of the states obtains.

>- A \textcolor{red}{Utility Function} is an assignment of \textcolor{red}{cardinal} utilities to consequences. The distinction between \textcolor{red}{cardinal} utilities and \textcolor{red}{ordinal} utilities is in your required reading for this week.

>- Here is the utility function for the dinner party example:
\bigskip
\begin{center}
\begin{tabular}{|c |c |c|}\hline
    & Fish  & Lamb \\ \hline
White & 5 & 2 \\ 
Red  & 1 & 5 \\ \hline
\end{tabular}
\end{center}

# Decision Problems: Consequences and Loss Functions

>- Instead of basing decisions on \textcolor{red}{favorable consequences} i.e., utilities; we can take the "pessimistic route" and base decisions by weighing \textcolor{red}{unfavorable} consequences, i.e., losses. 

>- Losses are "really" just \textcolor{red}{negative utilities}. One person's gain is another person's loss?

>- So we can in principle solve most decision problems using either utilities or losses. It just involves a shift in perspective.

>- But! the principles that make a choice \textcolor{red}{rational} will not be same. We'll come back to this later.

>- Here is President Biden's \emph{hypothetical} loss function.
\bigskip
\begin{center}
\begin{tabular}{|p{0.2\textwidth}| p{0.2\textwidth} p{0.3\textwidth}|}\hline
       & Deal  & No Deal \\ 
Invoke$^{c}$ & 0 & -10 \\ 
Invoke  & -1 & -1 \\ \hline
\end{tabular}
\end{center}


# Decision Problems: Rational Choice

>- We are now in a position to formulate some principles of rational choice that could form the basis of an inductive logic as the logic of reliable on-going scientific inquiry or rational deliberation.

>- First let us assume that states can be modeled as random variables with some probability distribution. That is, suppose that we have some \textcolor{red}{epistemic probability} $p_{i}$ that $S_{i}$ will happen.

>- Then we can use this epistemic probability $p_{i}$ to weigh the states and compute the \textcolor{red}{expected value} of functions of these states.

>- Since consequences are joint functions of acts and states, we can calculate the expected value of taking an act $A_{i}$, given state $S_{i}$.

>- This will lead to the concept of expected utility or expected loss (or risk)











