---
title: | 
  | Phil/LPS 31 Introduction to Inductive Logic
  | Lecture 1
author: |
    | David Mwakima
    | dmwakima@uci.edu
    | Department of Logic and Philosophy of Science
    | University of California, Irvine
date: "April 3rd 2023"
output: beamer_presentation
header-includes:
  - \setbeamertemplate{footline}[page number]
---

# Topics

\begin{itemize}

\item Logic in General

\item Sentences

\item Truth-functional connectives

\item Sentential logic

\end{itemize}

# Logic in General

>- A logic is a \textcolor{red}{formal system} for representing something whose \textcolor{red}{structure}, as opposed to \textcolor{red}{content}, we wish to describe.

>- The word "formal" here means that in logic we are concerned with the \textcolor{red}{form}, i.e., \textcolor{red}{uninterpreted symbols or formulas}, not their \textcolor{red}{material content}. Inevitably, this will involve both \textcolor{red}{abstraction} and \textcolor{red}{idealization}.

>- This distinction between "form" and "content" is crucial to understand a logic in general because logicians distinguish between the formal aspect of a language (\textcolor{red}{syntax}) and its content, meaning or interpretation (\textcolor{red}{semantics}). 

>- Finally, the word "system" means that given (1) these symbols and (2) rules of transforming these symbols; we can get (3) other symbols that also \textcolor{red}{belong to the representation}. The symbols that belong to the representation are called, you guessed it, \textcolor{red}{formulas}!

***

# Toy Example of a Logic\footnote{This example is from Gerstein, "Introduction to Mathematical Structures and Proofs" p. 3}

>- The symbols are $a$, $b$ and $S$.

>- The rules of transformation are: \begin{enumerate} \item S is a formula. 
\item The result of replacing $S$ with $aSb$ is a formula.
\item The result of deleting $S$ and closing up any resulting space is a formula.
\end{enumerate}

>- Closure condition: A formula is anything that results from 1 or a \textcolor{red}{finite number} of applications of rule 2 or rule 3. Nothing else is a formula.

>- Verify that all these are examples of formulas of the logic: $S$, $ab$, $aaSbb$, $aabb$. 

***

# Sentential Logic: Sentences

>- Sentential logic is a logic for representing the \textcolor{red}{sentence structure} of a fragment or piece of natural language. The natural language in our case will be English.

>- Philosophers like to distinguish between \textcolor{red}{sentences} and \textcolor{red}{propositions}. 

>- A sentence is a \textcolor{red}{linguistic} expression (a declarative statement in some language), which expresses a proposition. 

>- Different sentences can express the \textcolor{red}{same} proposition, e.g., if they are in different languages.
\begin{itemize} \item Schnee ist weiß (German) \item Snow is white (English) \end{itemize}

>- It turns out that saying what "propositions" are is a \textcolor{red}{hard} philosophical problem. So we'll stick to sentences!

***

# Sentential Logic: Sentences

>- I assume we all know what a sentence is.

>- But! For this class (or, more specifically \textcolor{red}{classical logic}) a sentence must be \textcolor{red}{unambiguously true} or \textcolor{red}{false}. This is just a convenient restriction.

>- Examples of sentences: \begin{enumerate}  \item The number two is an even prime number.
\item Kamala Harris was not a California Senator.
\item Michelle Yeoh won an Oscar Award.
\end{enumerate}

>- The following examples are not sentences (in our sense) because their truth value is either \textcolor{red}{context dependent} or \textcolor{red}{vague}: 
\begin{enumerate}  
\item He did it yesterday.
\item This is black.
\item There will be a sea battle tomorrow.
\item Having 1001 strands of hair does not make you bald. How about 1000, 999, \dots?
\end{enumerate}

***

# Sentential Logic: Truth-functional connectives

>- Consider the following sentences, call these \textcolor{red}{Case 1}: \begin{enumerate}
\item The number two is an even number \textcolor{red}{and} the number two is prime.
\item Kamala Harris was \textcolor{red}{not} California Senator.
\item Either Michelle Yeoh won an Oscar Award for Best Actress \textcolor{red}{or} Ana de Armas won an Oscar Award for Best Actress.
\item \textcolor{red}{If} today is Tuesday, \textcolor{red}{then} tomorrow is Wednesday.
\end{enumerate}

>- Each of these sentences, is really a compound sentence of two \text{simpler} sentences joined together by a "\textcolor{red}{connective}". But so are these sentences, call these \textcolor{red}{Case 2}: \begin{enumerate} \item David is teaching \textcolor{red}{until} his students are having fun. (True)
\item Ukraine is fighting Russia \textcolor{red}{until} Russia occupies Crimea. (False)
\item The students are having fun \textcolor{red}{because} the students like to study logic. (True)
\item  The students like to study logic \textcolor{red}{because} the discussions are early in the morning. (False)
\end{enumerate}

>- What's the difference between the sentences in \textcolor{red}{Case 1} and \textcolor{red}{Case 2}?

# Sentential Logic: Truth-functional connectives

>- In \textcolor{red}{Case 1}, the truth-value of the compound sentence is \textcolor{red}{uniquely and fully determined} by the truth-values of the simpler sentences it is composed of.

>- The connectives (\textcolor{red}{and}, \textcolor{red}{not}, \textcolor{red}{or}, \textcolor{red}{if..., then...}) in \textcolor{red}{Case 1} are said to be \textcolor{red}{truth-functional}.

>- In contrast, the connectives (\textcolor{red}{until}, \textcolor{red}{because}) in \textcolor{red}{Case 2} are not \textcolor{red}{truth-functional}. In order to determine the truth-value of the compound sentences which involve them, we need \textcolor{red}{extra information} beyond the truth-value of the simpler sentences. 

>- Sentential logic is the logic for representing the sentence structure of a fragment of natural language using truth-functional connectives.

# Sentential Logic: The Logic Itself

>- We are now in a position to describe sentential logic itself. I need: (1) formal symbols, (2) rules of transformation for getting formulas and (3) a closure condition.

>- The \textcolor{red}{formal symbols} of sentential logic are:
\begin{enumerate} \item \textcolor{red}{$p$}, \textcolor{red}{$q$}, \textcolor{red}{$r$}, \textcolor{red}{$s$} and \textcolor{red}{$t$} as symbols for sentences. If we need more than 5 symbols (rarely!), then add the following countably many symbols \textcolor{red}{$p_{1}$}, \textcolor{red}{$p_{2}$}, \textcolor{red}{$p_{3}$}, \dots.
\item \textcolor{red}{$\vee$} for "or", \textcolor{red}{$\lnot$} for "not" since the other symbols for "and" and "if..., then..." can be defined from these. (More of this later)
\item \textcolor{red}{$($} for left bracket and \textcolor{red}{$)$} for right bracket.
\end{enumerate}

>- The \textcolor{red}{transformation rules} (also known as "syntactic rules") are:
\begin{enumerate}
\item Any sentence \textcolor{red}{$p$} is a formula.
\item If \textcolor{red}{$p$} is a formula, then \textcolor{red}{$\lnot p$} is formula.
\item If \textcolor{red}{$p$} is a formula and \textcolor{red}{$q$} is a formula, then \textcolor{red}{$(p \vee q)$} is a formula.
\end{enumerate}

>- The \textcolor{red}{closure condition} states that a formula of sentential logic is anything that results from 1 or a \textcolor{red}{finite number} applications of rule 2 or rule 3. Nothing else is a formula of sentential logic.
