---
title: | 
  | Phil/LPS 31 Introduction to Inductive Logic
  | Lecture 4
author: |
    | David Mwakima
    | dmwakima@uci.edu
    | Department of Logic and Philosophy of Science
    | University of California, Irvine
date: "April 10th 2023"
output: beamer_presentation
header-includes:
  - \setbeamertemplate{footline}[page number]
---

# Topics

\begin{itemize}
\item Quantified Relational Logic: Motivation

\item Quantified Relational Logic: Variables and Quantifiers

\item Quantified Relational Logic: Predicates and Relations

\item Quantified Relational Logic: The Logic Itself
\end{itemize}

# Quantified Relational Logic: Motivation

>- So far, in sentential logic, we have taken \textcolor{red}{the basic unit of the analysis} of the structure of a natural language like English to be \textcolor{red}{sentences} and \textcolor{red}{truth-functional connectives} for combining simple sentences to make more complex sentences.

>- This was useful. But it was also too simple. It was too simple because we abstracted away the internal composition of sentences except the truth-functional connectives (\textcolor{red}{not, and, either...or..., if..., then...}) 

>- Now consider the following argument:\begin{itemize}\item[1] All logicians are wise.\item[2] Ruth Barcan Marcus is a logician.\item[$\therefore$3] Ruth Barcan Marcus is wise.
\end{itemize}

>- This argument is valid, (and sound!) but sentential logic cannot explain why.

# Quantified Relational Logic: Motivation

>- Now consider: \begin{itemize} \item[1a.] Hypatia is wise. \item[1b.] Hypatia possesses wisdom.\end{itemize} Sentential logic will paraphrase both 1a. and 1b. in the same way. 

>- But full \textcolor{red}{grammatical} sentences in English also have \textcolor{red}{proper names} for \textcolor{red}{individuals}, who stand in certain \textcolor{red}{relations} to other individuals, themselves, or concrete and abstract objects.

>- So we need a logic with more \textcolor{red}{expressive power} to represent not only the truth-functional structure of sentences in a natural language like English, but also their internal or grammatical structure. This logic is called \textcolor{red}{quantified relational logic} or \textcolor{red}{first order logic}.

>- This logic will allow us to say why the argument we started with earlier is deductively valid.

# Quantified Relational Logic: Variables and Quantifiers

Consider the following sentences:
\begin{itemize}
\item[(1)] Hypatia is wise.
\item[(2)] Cavendish is wise.
\item[(3)] Hypatia is female.
\item[(4)] Cavendish is female.
\end{itemize}

>- Fundamental to quantified relational logic is the notion of \textcolor{red}{a variable} and \textcolor{red}{a quantifier}, which we use \textcolor{red}{to generalize}.

>- Look at (1) and (2), if we want to generalize from these two sentences, we can drop the proper names 'Hypatia' and 'Cavendish' and simply say that:\begin{itemize} 
\item[(6)] Someone is wise.
\end{itemize}

>- If the \textcolor{red}{universe of discourse} involves only Hypatia and Cavendish we generalize and say that:
\begin{itemize} 
\item[(7)] Everyone is wise.
\end{itemize}

# Quantified Relational Logic: Variables and Quantifiers
\begin{center}
\begin{itemize} 
\item[(6)] Someone is wise.
\end{itemize}

\begin{itemize} 
\item[(7)] Everyone is wise.
\end{itemize}
\end{center}

>- In quantified relational logic, we paraphrase (6) and (7) as:
\begin{itemize}
\item[(8)] $\exists x$ ($x$ is wise)\,\,\,Read as "There exists an $x$ such that $x$ is wise."
\item[(9)] $\forall x$ ($x$ is wise)\,\,\,Read as "For all $x$, $x$ is wise." or "Every $x$ is wise."
\end{itemize}

>- In your \textcolor{red}{Homework 3} you will practice with these sorts of paraphrases. But this is not the main focus of the class. I just want to cover this because we will need it to understand things we will talk about later in week 2 or early week 3.

# Quantified Relational Logic: Variables and Quantifiers

>- The situation involving variables here is not different from that of high school algebra where variables were used, except that you didn't see the symbols  $\exists$ or $\forall$.

>- In high school algebra there were facts such as the following:
\begin{itemize}
\item[(10)] $4^2 - 2^2 = (4 - 2)(4 + 2)$
\end{itemize}

>- Since (10) is true for some numbers, namely 4 and 2, we can generalize and say:
\begin{itemize}
\item[(11)] $\exists x \exists y (x^2 - y^2 = (x - y)(x + y))$
\end{itemize}

>- In fact, (10) is true not just for some two numbers but \textcolor{red}{any} two numbers. So we can generalize even further and say:
\begin{itemize}
\item[(12)] $\forall x \forall y (x^2 - y^2 = (x - y)(x + y))$
\end{itemize}

>- We will not have to represent anything crazy like (11) and (12) for this class, but you will need to have an idea similar to what happens in high school algebra to understand what is going on.

# Quantified Relational Logic: Variables and Quantifiers

Let us go back to some of our original sentences:
\begin{itemize}
\item[(1)] Hypatia is wise.
\item[(2)] Cavendish is wise.
\end{itemize}

We said we can represent (1) and (2) as either as:\begin{itemize} 
\item[(6)] Someone is wise, or
\item[(7)] Everyone is wise.
\end{itemize}

Or symbolically as: \begin{itemize}
\item[(8)] $\exists x$ ($x$ is wise) 
\item[(9)] $\forall x$ ($x$ is wise)
\end{itemize}

>- The symbols $\exists$ and $\forall$ are called \textcolor{red}{quantifiers}. $x$ is a called a \textcolor{red}{variable} that is \textcolor{red}{bound} by that quantifier.

# Quantified Relational Logic: Variables and Quantifiers

Using quantifiers and variables generalize the other two sentences we started with assuming that the universe of discourse includes only Hypatia and Cavendish.
\begin{itemize} \item[(3)] Hypatia is female. \item[(4)] Cavendish is female.\end{itemize}.

# Quantified Relational Logic: Predicates and Relations

Now consider all four of our original sentences:\begin{itemize}
\item[(1)] Hypatia is wise.
\item[(2)] Cavendish is wise.
\item[(3)] Hypatia is female.
\item[(4)] Cavendish is female.
\end{itemize}

>- Notice that there is \textcolor{red}{variation} in proper names ("Hypatia", "Cavendish") and what comes after the proper name ("is wise", "is female"), which are both \textcolor{red}{one place relations}.

>- But! what is \textcolor{red}{is common} between all four sentences is their \textcolor{red}{logical form}. They are all of the logical form:
\begin{center}
<subject> + <one place relation>
\end{center}

# Quantified Relational Logic: Predicates and Relations.

\begin{itemize}
\item[(1)] Hypatia is wise.
\item[(2)] Cavendish is wise.
\item[(3)] Hypatia is female.
\item[(4)] Cavendish is female.
\end{itemize}

>- We have already seen how to generalize when the subject of a sentence is a proper name. We introduced symbols for quantifiers (\textcolor{red}{$\exists$} and \textcolor{red}{$\forall$}) and variables (\textcolor{red}{$x, y$}).

>- How do we generalize sentences which have \textcolor{red}{the same} logical form:
\begin{center}
<subject> + <one place relation> ?
\end{center}

>- We introduce the relational symbol \textcolor{red}{$W$} for the relation "is wise" and paraphrase (1) and (2) as:\begin{itemize} \item[(14)] $Wx$ \,\,\, Read as "$x$ is $W$" \item[(15)] $Wy$ \,\,\,  Read as "$y$ is $W$" \end{itemize} 

# Quantified Relational Logic: Predicates and Relations.

\begin{itemize}
\item[(1)] Hypatia is wise.
\item[(2)] Cavendish is wise.
\item[(3)] Hypatia is female.
\item[(4)] Cavendish is female.
\end{itemize}

>- Introduce the relational symbol \textcolor{red}{$F$} for the relation "is female" and paraphrase (3) and (4):


# Quantified Relational Logic: Predicates and Relations

\begin{itemize}
\item[(1)] Hypatia is wise.
\item[(2)] Cavendish is wise.
\item[(3)] Hypatia is female.
\item[(4)] Cavendish is female.
\end{itemize}

>- So the structure of (1), (2) can be represented most generally using quantified relational logic as either: 
\begin{itemize}
\item[(16)] $\exists x Wx$ \,\,\, Read as "There exists an $x$ and $x$ is $W$", or
\item[(17)] $\forall x Wx$ \,\,\, Read as "Every $x$ is $W$".
\end{itemize}

# Quantified Relational Logic: Predicates and Relations

Using appropriate symbols for quantifiers, variables and relations, paraphrase or formalize the following sentences in quantified relational logic:
\begin{itemize}
\item[(3)] Hypatia is female.
\item[(4)] Cavendish is female.
\end{itemize}

# Quantified Relational Logic: Predicates and Relations

Now consider the following sentences:
\begin{itemize}
\item[(1)] Hypatia is wise.
\item[(18)] Hypatia possesses wisdom.
\item[(19)] Ottoline met Russell.
\end{itemize}

>- While (1) and (18) appear to mean the same thing, they have different logical form. (1) is of the form:
\begin{center}
<subject> + <\textcolor{red}{one} place relation>
\end{center} while (18) is of the form:
\begin{center}
<subject> + <\textcolor{red}{two} place relation> + <object>
\end{center}

>- Similarly (19) is also of the form:\begin{center}
<subject> + <\textcolor{red}{two} place relation> + <object>
\end{center}

>- The numbers \textcolor{red}{one} and \textcolor{red}{two} that tell us how many subjects or objects ("one place" or "two place") a relation needs in a full grammatical sentence of English are called the \textcolor{red}{arity} of the relation.

# Quantified Relational Logic: Predicates and Relations

There is a special name for relations whose \textcolor{red}{arity is one}. They are called \textcolor{red}{predicates}. "is wise", "is female" are all predicates.

To paraphrase sentences like:\begin{itemize}\item[(18)] Hypatia possesses wisdom.
\item[(19)] Ottoline met Russell.
\end{itemize} we introduce symbols for 2-place or \textcolor{red}{binary} relations and use \textcolor{red}{different variables} for all the \textcolor{red}{distinct} subjects or objects that stand in the relation.

>- So (18) can be paraphrased as:\begin{center} \textcolor{red}{$Pxy$}\,\,\, Read as "x possesses y" \end{center} Here we chose the variable \textcolor{red}{$x$} to stand for Hypatia and the variable \textcolor{red}{$y$} to stand for wisdom and the relational symbol \textcolor{red}{$P$} to stand for the two place relation $<x$ possesses $y>$.

>- Once we made this choice, the correct paraphrase was $Pxy$ not $Pyx$! So with relations \textcolor{red}{order matters!}

# Quantified Relational Logic: Predicates and Relations

\begin{itemize}
\item[(18)] Hypatia possesses wisdom.
\item[(19)] Ottoline met Russell.
\end{itemize}

>- Once we have paraphrased $(18)$ as $Pxy$ we can use quantifiers and variables to generalize $(18)$ as:
\begin{center}
$\exists x \exists y Pxy$
\end{center}

# Quantified Relational Logic: Predicates and Relations

\begin{itemize}
\item[(18)] Hypatia possesses wisdom.
\item[(19)] Ottoline met Russell.
\end{itemize}

Using the symbol $M$ for the relation $<x$ met $y>$ paraphrase (19) with full generality.

# Quantified Relational Logic: The Logic Itself

>- We are now in a position do describe quantified relational logic for \textcolor{red}{one} or \textcolor{red}{two} place relations \textcolor{red}{only}. Remember that to specify a logic I need to tell you (1) the formal symbols, (2) the transformation rules, and (3) closure condition.

>- The \textcolor{red}{formal symbols} are:
\begin{itemize}
\item \textcolor{red}{a, b, c, \dots, m, n, \dots} as symbols for \textcolor{red}{terms}. A term is anything in a theory or language that can be given a proper name or an object that can be identified uniquely.
\item \textcolor{red}{x, y, z} as symbols for \textcolor{red}{variables}, which range over terms.
\item Upper case letters \textcolor{red}{$P, Q, R, S, T, \dots, A, B, C, D,\dots, M, \dots$} of the English alphabet as symbols for \textcolor{red}{relations} (one or two place only).
\item Truth-functional connectives: \textcolor{red}{$\vee$, $\wedge$, $\lnot$, $\to$, $\leftrightarrow$}
\item Quantifiers: \textcolor{red}{$\forall$, $\exists$}
\item Brackets: \textcolor{red}{(} for left bracket and \textcolor{red}{)} for right bracket.
\end{itemize}

# Quantified Relational Logic: The Logic Itself

>- The \textcolor{red}{transformation rules} are:
\begin{itemize}
\item[1] For any predicate symbol $P$ and for any two place relation symbol $R$, given any constants $a$ or $b$ or any variables $x$ or $y$, $Pa$, $Px$, $Rab$, $Rxy$ are formulas. In $Px$ and $Rxy$ formulas, $x$ and $y$ are said to \textcolor{red}{"free"} variables because there are no quantifiers to which they are \textcolor{red}{bound}.
\item[2] If $Px$ is a formula, then $(\exists x Px)$ is a formula and $(\forall x Px)$ is a formula. Rule 2 is known as \textcolor{red}{binding} any free variable in $Px$ by a quantifier.
\item[3] If $Rxy$ is a formula, then $(\exists x Rxy)$ is a formula and $(\forall x Rxy)$ is a formula. Here $y$ is a free variable but $x$ is bound.
\end{itemize}

# Quantified Relational Logic: The Logic Itself

In order to talk about formulas at a meta-level we use the symbols $\mathcal{F}, \mathcal{G}$ and $\mathcal{H}$ and say:
\begin{itemize}
\item[4] If $\mathcal{F}$ is a formula by rule 3, then the result of \textcolor{red}{binding} any free variable in $\mathcal{F}$ is and closing everything up with one left and one right parenthesis is a formula.

\item[5] A formula $\mathcal{F}$ formed by either rule 1, 2, 3 or 4 is called an \textcolor{red}{atomic formula}.

\item[6] If $\mathcal{F}$ and $\mathcal{G}$ are atomic formulas then $(\mathcal{F} \vee \mathcal{G})$, $(\mathcal{F} \wedge \mathcal{G})$, $\lnot \mathcal{F}$, $(\mathcal{F} \to \mathcal{G})$ and $(\mathcal{F} \leftrightarrow \mathcal{G})$ are \textcolor{red}{molecular formulas}.
\item[7] If $\mathcal{H}$ is a molecular formula, then the result of \textcolor{red}{binding} any free variable in $\mathcal{H}$ is formula and closing everything up with one left and one right parenthesis is a formula. 
\end{itemize}

# Quantified Relational Logic: The Logic Itself

>- The \textcolor{red}{Closure Condition} says that a formula of quantified relational logic is either an atomic formula or a molecular formula built from atomic formulas by \textcolor{red}{finite applications} of rule 5 and 6. Nothing else is a formula.

>- We have now characterized the syntax of quantified relational logic. Next time we will introduce some inference rules for doing deduction in quantified relational logic, and talk about the interpretation or semantics of quantified relational logic very briefly.














































































